######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 7 20:51:20 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mywindow.h
SOURCES += main.cpp mywindow.cpp
